name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dockerfile  # Nome do seu ambiente no GitHub

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME }}  # O nome do segredo deve ser exatamente como definido no ambiente
        password: ${{ secrets.PASS }}      # O nome do segredo deve ser exatamente como definido no ambiente

    - name: Build and tag Docker image
      run: docker build . --file Dockerfile --tag thirerys:$(date +%s) --tag thirerys:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push thirerys:$(date +%s)
        docker push thirerys:latest
