name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dockerfile

    steps:
    - uses: actions/checkout@v3

    - name: Define TIMESTAMP
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}

    - name: Build and tag Docker image
      run: |
        docker build . --file Dockerfile --tag avelino12/thierrys:$TIMESTAMP --tag avelino12/thierrys:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push avelino12/thierrys:$TIMESTAMP
        docker push avelino12/thierrys:latest
#teste